apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask
  template:
    metadata:
      name: my-flask-pod
      labels:
        app: my-flask
    spec:
      containers:
        - name: my-flask-container
          image: gnstkd/myflask:1.0
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-service
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.4
  ports:
    - name: my-flask
      port: 5000
      targetPort: 5000
  selector:
    app: my-flask
