apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-react-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-react
  template:
    metadata:
      name: my-react-pod
      labels:
        app: my-react
    spec:
      containers:
        - name: my-react-container
          image: gnstkd/myreact:1.0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-react-service
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.5
  ports:
    - name: my-react
      port: 80
      targetPort: 80
  selector:
    app: my-react
