apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-persistentvolumeclaim
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nfs-mount-container
spec:
  containers:
    - name: nfs-mount-container
      image: docker.io/busybox
      args: ["tail", "-f", "/dev/null"]
      volumeMounts:
        - name: nfs-volume
          mountPath: /mnt
  imagePullSecrets:
    - name: regcred
  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-persistentvolumeclaim
